# Build stage
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

# Copy csproj and restore as distinct layers
COPY *.sln .
COPY tycoonAPI/*.csproj ./tycoonAPI/
RUN dotnet restore

# Copy the rest of the code
COPY tycoonAPI/. ./tycoonAPI/
WORKDIR /src/tycoonAPI
RUN dotnet publish -c Release -o /app/publish

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

# Tell Render what port the app will run on
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

# Start the app
ENTRYPOINT ["dotnet", "tycoonAPI.dll"]
